[workspace]

[package]
version = "0.1.0"
name = "mm-sp1-guest"
edition = "2021"

[dependencies]
sp1-zkvm = "3.4.0"
mmtokens = { path = "../../common/mmtokens" }
mmlib = { path = "../../common/mmlib", default-features = false, features = ['use_hints'] }